### PR TITLE
Add customization/generated-artifact validation

### PR DESCRIPTION
**Pull request by mezarin**
This PR adds validation to be sure that the output/generated stack artifact entries contain the customization values specified in the customization files (customize-ol.env and customize-wl.env). Validation takes place as part of the build process for development and as a PR test for those cases where the user may forget to build the stack artifacts after having customized the stack.

Sample error message:
```
ERROR: One or more customization value entries in file customize-wl.env were not found in the respective output files in the "/stack" directory. Verify that the build.sh command ran successfully.
Error message:
MAVEN_VERSION value: 3.6.3.something was not found in file: /home/runner/work/devfile-stack-test/devfile-stack-test/stack/websphere-liberty/image/maven/Dockerfile.
STACK_IMAGE_MAVEN value: something.icr.io/appcafe/websphere-liberty-devfile-stack:{{liberty-version}} was not found in file: /home/runner/work/devfile-stack-test/devfile-stack-test/stack/websphere-liberty/devfiles/maven/devfile.yaml.
STACK_IMAGE_MAVEN value: something.icr.io/appcafe/websphere-liberty-devfile-stack:${LIBERTY_VERSION} was not found in file: /home/runner/work/devfile-stack-test/devfile-stack-test/stack/websphere-liberty/outer-loop/maven/Dockerfile.
STACK_IMAGE_GRADLE value: something.icr.io/appcafe/websphere-liberty-devfile-stack:{{liberty-version}}-gradle was not found in file: /home/runner/work/devfile-stack-test/devfile-stack-test/stack/websphere-liberty/devfiles/gradle/devfile.yaml.
STACK_IMAGE_GRADLE value: something.icr.io/appcafe/websphere-liberty-devfile-stack:${LIBERTY_VERSION}-gradle was not found in file: /home/runner/work/devfile-stack-test/devfile-stack-test/stack/websphere-liberty/outer-loop/gradle/Dockerfile.
```

### CODE REVIEW

**Review by scottkurz — CHANGES_REQUESTED** [review]
I don't know if validating DURING the execution of build.sh is really that helpful.   It slows it down quite a bit, to about 25s for me..tempting me to want to bypass it ;) 

It's not especially what I had in mind since the main "use case" I'm concerned with is the user forgetting to run build.sh altogether, since it's "just a minor change".   In some cases, this will be true.. but I'm just trying to guard against someone forgetting to run it.

So I'd just have a simple **validate.sh** with no args, and run it during GHA.. but also make it work locally from your laptop if possible.

**Comment by mezarin** [comment]
I am not sure what it takes so long on your system. On mine it takes at most a second to run.
As i mentioned this serves two purposes. Catch errors during "development" (update scripts/customization/Dockerfile/devfile, etc) and catch errors on cases where only the customization files are updated. 
Again the purpose of running validation during build time is for "development". Erroneous updates to the scripts/Dockerfiles/etc can cause some customization not to be changed and not caught during manual inspection. It would be nice to have some automated way at build time to catch those errors prior to pushing a commit and wait for the tests to run for it to get caught.

**Review by scottkurz — APPROVED** [review]
This looks good.   Let's go with it.  

IIUC, there are a couple things that could slip through the cracks (please correct me if I'm wrong):

1.  If two of the customization values ever end up the same... e.g. liberty-maven-plugin v3.6.3 and maven 3.6.3... does the validation really distinguish?   Maybe not that likely but noting.
2. If say I were to do something like add a second usage of one of these customization vars, I don't think the validation would detect.  E.g. say we added a whole other devfile cmd starting with:
>       commandLine: mvn -DinstallDirectory={{.WLP_INSTALL_PATH}}
I think the script would still show 'valid' even if we forgot to run the `build.sh`

I think the fix for the above would be to switch strategies to just running the `build.sh` and doing a diff.     If you want to take it in that direction that's fine with me, or if you want to ship and we'll pick this up if we ever want/need to, that's fine too.

Thanks.

**Comment by mezarin** [comment]
Thanks for taking a look. If i am understanding the cases correctly, I believe the concerns you have are handled by the last update. The purpose of doing it this way is to detect script update issues prior to merging the code (when running build.sh. i.e. "unit" test) and after merging the code (forgot to run build.sh). The latter being the case you are most concerned about. I agree that the validation being introduced does not care that the merged output files are not exactly the same (i.e. comments, or anything that is not associated to customization parameters in the customization files) as the build.sh output. So, perhaps we can address the part you are more concerned about with a separate test that just diffs the files.

**Review by scottkurz — APPROVED** [review]
LGTM

**Pull request merged**
